stages:
  prepare:
    cmd: python -m model_training.data_prep          # ← run as a package
    deps:
      - data/raw/a1_RestaurantReviews_HistoricDump.tsv
      - src/model_training/data_prep.py                           
      - src/model_training/config.py                              
    outs:
      - data/preprocessed
  train:
    cmd: python -m model_training.train
    deps:
      - data/preprocessed
      - src/model_training/train.py
      - src/model_training/config.py                              
    outs:
      - models

  evaluate:
    cmd: python -m model_training.evaluate
    deps:
      - models
      - src/model_training/evaluate.py
      - src/model_training/config.py     
      - data/preprocessed
    metrics:
      - reports/metrics.json:
          cache: false