stages:
  prepare:
    cmd: python src/data_prep.py
    deps:
    - data/raw/a1_RestaurantReviews_HistoricDump.tsv
    - src/data_prep.py
    outs:
    - data/preprocessed
  train:
    cmd: python src/train.py
    deps:
    - data/preprocessed
    - src/train.py
    outs:
    - models
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - models
    - data/preprocessed
    metrics:
    - data/metrics.json:
        cache: false
