stages:
  prepare:
    cmd: python src/data_prep.py
    deps:
    - data/a1_RestaurantReviews_HistoricDump.tsv
    - src/data_prep.py
    outs:
    - data/processed.csv
  train:
    cmd: python src/train.py
    deps:
    - data/processed.csv
    - src/train.py
    outs:
    - data/predictions.csv
    - models/c1_BoW.pkl
    - models/c2_model.pkl
  evaluate:
    cmd: python src/evaluate.py
    deps:
    - data/predictions.csv
    - src/evaluate.py
    metrics:
    - metrics.json:
        cache: false
