name: Release lib-ml

on:
  push:
    tags:
      - 'v*.*.*'  
jobs:
  release:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v3
        
      - uses: iterative/setup-dvc@v1
      - run: |
          dvc pull .\data\raw\a1_RestaurantReviews_HistoricDump.tsv
          dvc repro
          dvc push --verbose -r drive
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_SECRET }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:                        
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name:      ${{ github.ref_name }}
          release_name:  ${{ github.ref_name }}
          body: |
            Automated release of sentiment-analysis models
          draft: false
          prerelease: false

      - name: Upload BoW sentiment model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:           ${{ steps.create_release.outputs.upload_url }}
          asset_path:           c1_BoW_Sentiment_Model.pkl
          asset_name:           c1_BoW_Sentiment_Model.pkl
          asset_content_type:   application/octet-stream

      - name: Upload classifier sentiment model
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url:           ${{ steps.create_release.outputs.upload_url }}
          asset_path:           c2_Classifier_Sentiment_Model
          asset_name:           c2_Classifier_Sentiment_Model
          asset_content_type:   application/octet-stream
