name: Release lib-ml

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        token: ${{ secrets.GITHUB_TOKEN }}     
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated release of sentiment‐analysis models.
          draft: false
          prerelease: false

      # Upload the first model artifact
      - name: Upload BoW sentiment model
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./c1_BoW_Sentiment_Model.pkl
          asset_name: c1_BoW_Sentiment_Model.pkl
          asset_content_type: application/octet-stream

      # Upload the second model artifact
      - name: Upload classifier sentiment model
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./c2_Classifier_Sentiment_Model.pkl
          asset_name: c2_Classifier_Sentiment_Model.pkl
          asset_content_type: application/octet-stream
